---
- name: Configure Jenkins Server.
  hosts: server
  sudo: True
  pre_tasks:
    - name: Update Server
      raw: sudo apt-get update
  
  roles: 
    - geerlingguy.jenkins 
    - mrlesmithjr.netdata